"""
VMotionLab - Report Generator
=============================

This module generates a PDF report for a VMotionLab project.

Report includes:
- Project/session metadata
- Camera and recording information
- Processing information
- Clinical angle convention
- Angle calculation limitations
- Kinematics statistics
- Kinematic figures
- Output file summary

This module does not contain Streamlit UI code.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
from fpdf import FPDF

from modules.clinical_notes import (
    REPORT_ANGLE_CONVENTION_TEXT,
    REPORT_ANGLE_LIMITATION_TEXT,
)


REPORT_DIRNAME = "report"
REPORT_FILENAME = "report.pdf"
REPORT_INFO_FILENAME = "report_info.json"

STATISTICS_FILENAME = "statistics.csv"
NORMALIZED_CURVES_FILENAME = "normalized_curves.csv"
MULTI_TRIAL_MEAN_SD_FILENAME = "multi_trial_mean_sd.csv"
MULTI_TRIAL_STATISTICS_FILENAME = "multi_trial_statistics.csv"
MULTI_TRIAL_INFO_FILENAME = "multi_trial_info.json"
PROCESSING_INFO_FILENAME = "processing_info.json"
KINEMATICS_INFO_FILENAME = "kinematics_info.json"
METADATA_FILENAME = "metadata.json"


def load_json(path: Path | str) -> Optional[Dict[str, Any]]:
    """Load JSON safely."""
    path = Path(path)

    if not path.exists():
        return None

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def save_json(path: Path | str, data: Dict[str, Any]) -> None:
    """Save dictionary as formatted JSON."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    path.write_text(
        json.dumps(data, indent=4, ensure_ascii=False),
        encoding="utf-8",
    )


def safe_text(value: Any) -> str:
    """
    Convert value to PDF-safe text.

    FPDF core fonts are safer with simple Latin text.
    """
    if value is None:
        return "-"

    text = str(value)

    replacements = {
        "°": " deg",
        "–": "-",
        "—": "-",
        "→": "->",
        "≤": "<=",
        "≥": ">=",
        "≈": "approximately",
        "•": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


def format_value(value: Any) -> str:
    """Format metadata/statistical values for report display."""
    if value is None:
        return "-"

    if isinstance(value, float):
        return f"{value:.2f}"

    if isinstance(value, int):
        return str(value)

    if isinstance(value, bool):
        return "Yes" if value else "No"

    return safe_text(value)


def read_statistics(project_path: Path | str) -> Optional[pd.DataFrame]:
    """Read statistics.csv if available."""
    project_path = Path(project_path)
    path = project_path / STATISTICS_FILENAME

    if not path.exists():
        return None

    try:
        return pd.read_csv(path)
    except Exception:
        return None


class VMotionLabPDF(FPDF):
    """Custom PDF class for VMotionLab report."""

    def header(self) -> None:
        self.set_font("Arial", "B", 12)
        self.cell(0, 8, "VMotionLab Motion Analysis Report", border=0, ln=True, align="C")
        self.ln(2)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(
            0,
            10,
            f"Generated by VMotionLab | Page {self.page_no()}",
            border=0,
            align="C",
        )


class ReportGenerator:
    """Generate VMotionLab PDF report."""

    def __init__(self, project_path: Path | str) -> None:
        self.project_path = Path(project_path)
        self.report_dir = self.project_path / REPORT_DIRNAME
        self.report_path = self.report_dir / REPORT_FILENAME
        self.report_info_path = self.report_dir / REPORT_INFO_FILENAME

        self.metadata = load_json(self.project_path / METADATA_FILENAME) or {}
        self.processing_info = load_json(self.project_path / PROCESSING_INFO_FILENAME) or {}
        self.kinematics_info = load_json(self.project_path / KINEMATICS_INFO_FILENAME) or {}
        self.statistics_df = read_statistics(self.project_path)

        self.pdf = VMotionLabPDF()
        self.pdf.set_auto_page_break(auto=True, margin=15)

    def add_title_page(self) -> None:
        """Add title and session summary."""
        self.pdf.add_page()

        self.pdf.set_font("Arial", "B", 18)
        self.pdf.cell(0, 12, "VMotionLab", ln=True, align="C")

        self.pdf.set_font("Arial", "", 12)
        self.pdf.cell(
            0,
            8,
        )

        self.pdf.ln(8)

        self.add_section_title("Session Information")

        rows = [
            ("Subject / Participant ID", self.metadata.get("subject_id")),
            ("Task", self.metadata.get("task")),
            ("Trial Name", self.metadata.get("trial_name")),
            ("Side", self.metadata.get("side")),
            ("Clinician / Operator", self.metadata.get("clinician")),
            ("Project Name", self.metadata.get("project_name")),
            ("Created At", self.metadata.get("created_at")),
            ("Report Generated At", datetime.now().isoformat(timespec="seconds")),
        ]

        self.add_key_value_table(rows)

        notes = self.metadata.get("notes")

        if notes:
            self.add_section_title("Notes")
            self.add_paragraph(notes)

    def add_section_title(self, title: str) -> None:
        """Add formatted section title."""
        self.pdf.ln(4)
        self.pdf.set_font("Arial", "B", 13)
        self.pdf.set_fill_color(235, 235, 235)
        self.pdf.cell(0, 8, safe_text(title), ln=True, fill=True)
        self.pdf.ln(2)

    def add_subsection_title(self, title: str) -> None:
        """Add formatted subsection title."""
        self.pdf.ln(3)
        self.pdf.set_font("Arial", "B", 11)
        self.pdf.cell(0, 7, safe_text(title), ln=True)

    def add_paragraph(self, text: Any) -> None:
        """Add paragraph text."""
        self.pdf.set_font("Arial", "", 10)
        self.pdf.multi_cell(0, 5, safe_text(text))
        self.pdf.ln(2)

    def add_key_value_table(self, rows: List[tuple[str, Any]]) -> None:
        """Add a two-column key-value table."""
        self.pdf.set_font("Arial", "", 9)

        key_width = 60
        value_width = 120

        for key, value in rows:
            self.pdf.set_font("Arial", "B", 9)
            self.pdf.cell(key_width, 6, safe_text(key), border=1)

            self.pdf.set_font("Arial", "", 9)
            self.pdf.cell(value_width, 6, format_value(value), border=1, ln=True)

        self.pdf.ln(2)

    def add_file_status_table(self) -> None:
        """Add project output file status table."""
        files = [
            ("Recording video", "recording.mp4"),
            ("Landmarks", "landmarks.csv"),
            ("Raw motion", "motion_raw.csv"),
            ("Trimmed motion", "motion_trimmed.csv"),
            ("Filtered motion", "motion_filtered.csv"),
            ("Processing info", "processing_info.json"),
            ("Statistics", "statistics.csv"),
            ("Normalized curves", "normalized_curves.csv"),
            ("Kinematics info", "kinematics_info.json"),
            ("PDF report", "report/report.pdf"),
        ]

        rows = []

        for label, relative_path in files:
            exists = (self.project_path / relative_path).exists()
            rows.append((label, f"{relative_path} - {'Found' if exists else 'Not found'}"))

        self.add_key_value_table(rows)

    def add_camera_recording_information(self) -> None:
        """Add camera and recording information from metadata."""
        self.add_section_title("Camera and Recording Information")

        camera = self.metadata.get("camera", {})
        recording = self.metadata.get("recording", {})

        if not camera and not recording:
            self.add_paragraph("Camera and recording information was not available.")
            return

        camera_rows = [
            ("Camera Index", camera.get("camera_index")),
            ("Reported Width", camera.get("reported_width")),
            ("Reported Height", camera.get("reported_height")),
            ("Reported FPS", camera.get("reported_fps")),
            ("Target Save FPS", camera.get("target_save_fps")),
            ("Mirror Camera", camera.get("mirror_camera")),
            ("Landmarks Drawn on Video", camera.get("draw_landmarks_on_video")),
        ]

        recording_rows = [
            ("Recorded At", recording.get("recorded_at")),
            ("Requested Duration", recording.get("requested_duration_seconds")),
            ("Actual Duration", recording.get("actual_duration_seconds")),
            ("Recorded Frames", recording.get("recorded_frames")),
            ("Actual Processing FPS", recording.get("actual_processing_fps")),
            ("Pose Detected Frames", recording.get("pose_detected_frames")),
            ("Pose Detection Rate (%)", recording.get("pose_detection_rate_percent")),
        ]

        self.add_subsection_title("Camera")
        self.add_key_value_table(camera_rows)

        self.add_subsection_title("Recording")
        self.add_key_value_table(recording_rows)

    def add_processing_information(self) -> None:
        """Add trim, preprocessing, and kinematics processing information."""
        self.add_section_title("Processing Information")

        processing = self.metadata.get("processing", {})

        if not processing:
            self.add_paragraph("Processing information was not available.")
            return

        trim = processing.get("trim")
        preprocessing = processing.get("preprocessing")
        kinematics = processing.get("kinematics")

        if trim:
            self.add_subsection_title("Trim Trial")
            rows = [
                ("Input File", trim.get("input_file")),
                ("Output File", trim.get("output_file")),
                ("Start Time Original (s)", trim.get("start_time_original_seconds")),
                ("End Time Original (s)", trim.get("end_time_original_seconds")),
                ("Selected Window (s)", trim.get("selected_window_seconds")),
                ("Raw Rows", trim.get("raw_rows")),
                ("Trimmed Rows", trim.get("trimmed_rows")),
                ("Time Rebased to Zero", trim.get("time_rebased_to_zero")),
                ("Frame Reset to Zero", trim.get("frame_reset_to_zero")),
            ]
            self.add_key_value_table(rows)

        if preprocessing:
            self.add_subsection_title("Preprocessing")

            sampling = preprocessing.get("sampling", {})
            interpolation = preprocessing.get("interpolation", {})
            filtering = preprocessing.get("filtering", {})

            rows = [
                ("Input File", preprocessing.get("input_file")),
                ("Output File", preprocessing.get("output_file")),
                ("Rows", preprocessing.get("rows")),
                ("Sampling Frequency (Hz)", sampling.get("sampling_frequency_hz")),
                ("Median dt (s)", sampling.get("median_dt_seconds")),
                ("Interpolation Requested", interpolation.get("requested")),
                ("Interpolation Applied", interpolation.get("applied")),
                ("Interpolation Method", interpolation.get("method")),
                ("Filtering Requested", filtering.get("requested")),
                ("Filtering Applied", filtering.get("applied")),
                ("Cutoff Frequency (Hz)", filtering.get("cutoff_frequency_hz")),
                ("Filter Order", filtering.get("order")),
            ]
            self.add_key_value_table(rows)

        if kinematics:
            self.add_subsection_title("Kinematics")
            rows = [
                ("Input File", kinematics.get("input_file")),
                ("Statistics File", kinematics.get("statistics_file")),
                ("Normalized Curves File", kinematics.get("normalized_curves_file")),
                ("Rows", kinematics.get("rows")),
                ("Duration (s)", kinematics.get("duration_seconds")),
                ("Normalize Points", kinematics.get("normalize_points")),
            ]
            self.add_key_value_table(rows)

    def add_clinical_notes(self) -> None:
        """Add clinical angle convention and limitations."""
        self.add_section_title("Clinical Angle Convention")
        self.add_paragraph(REPORT_ANGLE_CONVENTION_TEXT)

        self.add_section_title("Angle Calculation Limitations")
        self.add_paragraph(REPORT_ANGLE_LIMITATION_TEXT)


    def add_statistics_table(self) -> None:
        """Add statistics table from statistics.csv."""
        self.add_section_title("Kinematics Statistics")

        if self.statistics_df is None or self.statistics_df.empty:
            self.add_paragraph("statistics.csv was not available.")
            return

        display_columns = [
            "joint",
            "minimum_deg",
            "maximum_deg",
            "mean_deg",
            "sd_deg",
            "rom_deg",
            "initial_deg",
            "final_deg",
        ]

        available_columns = [
            column for column in display_columns if column in self.statistics_df.columns
        ]

        df = self.statistics_df[available_columns].copy()

        column_labels = {
            "joint": "Joint",
            "minimum_deg": "Min",
            "maximum_deg": "Max",
            "mean_deg": "Mean",
            "sd_deg": "SD",
            "rom_deg": "ROM",
            "initial_deg": "Initial",
            "final_deg": "Final",
        }

        widths = {
            "joint": 54,
            "minimum_deg": 18,
            "maximum_deg": 18,
            "mean_deg": 18,
            "sd_deg": 18,
            "rom_deg": 18,
            "initial_deg": 22,
            "final_deg": 22,
        }

        self.pdf.set_font("Arial", "B", 8)

        for column in available_columns:
            self.pdf.cell(widths.get(column, 20), 6, column_labels.get(column, column), border=1)

        self.pdf.ln()

        self.pdf.set_font("Arial", "", 8)

        for _, row in df.iterrows():
            if self.pdf.get_y() > 260:
                self.pdf.add_page()
                self.pdf.set_font("Arial", "B", 8)

                for column in available_columns:
                    self.pdf.cell(widths.get(column, 20), 6, column_labels.get(column, column), border=1)

                self.pdf.ln()
                self.pdf.set_font("Arial", "", 8)

            for column in available_columns:
                value = row.get(column)
                text = format_value(value)
                self.pdf.cell(widths.get(column, 20), 6, text[:28], border=1)

            self.pdf.ln()

        self.pdf.ln(2)
        self.add_paragraph("All angle values are reported in degrees.")

    def add_figures(self) -> None:
        """Add kinematic figures if available."""
        self.add_section_title("Kinematic Figures")

        figures = [
            ("Clinical Joint Angles Over Time", self.project_path / "figures" / "kinematics_time_curves.png"),
            ("Normalized Clinical Joint Angles", self.project_path / "figures" / "kinematics_normalized_curves.png"),
        ]

        found_any = False

        for title, image_path in figures:
            if not image_path.exists():
                continue

            found_any = True
            self.add_subsection_title(title)

            try:
                current_y = self.pdf.get_y()

                if current_y > 170:
                    self.pdf.add_page()

                self.pdf.image(str(image_path), x=15, w=180)
                self.pdf.ln(4)

            except Exception:
                self.add_paragraph(f"Could not insert figure: {image_path.name}")

        if not found_any:
            self.add_paragraph("No kinematic figures were available.")

    def add_multi_trial_section(self) -> None:
        """
        Add multi-trial analysis section if multi-trial outputs exist.
        """
        multi_stats_path = self.project_path / MULTI_TRIAL_STATISTICS_FILENAME
        multi_info_path = self.project_path / MULTI_TRIAL_INFO_FILENAME

        if not multi_stats_path.exists():
            return

        self.pdf.add_page()
        self.add_section_title("Multi-Trial Analysis")

        self.add_paragraph(
            "This section summarizes multi-trial analysis results when multiple "
            "normalized movement trials are selected. Mean and standard deviation "
            "are calculated across trials at each percentage point of the normalized "
            "0-100% movement cycle."
        )

        if multi_info_path.exists():
            try:
                multi_info = json.loads(multi_info_path.read_text(encoding="utf-8"))
                n_trials = multi_info.get("n_selected_projects", "-")
                primary_variable = multi_info.get("primary_variable", "-")

                self.add_key_value("Number of selected trials", n_trials)
                self.add_key_value("Primary variable", primary_variable)

            except Exception:
                self.add_paragraph("Multi-trial information file could not be read.")

        try:
            multi_stats_df = pd.read_csv(multi_stats_path)

            if not multi_stats_df.empty:
                self.pdf.ln(3)
                self.pdf.set_font("Arial", "B", 10)
                self.pdf.cell(0, 8, "Multi-Trial Summary Statistics", ln=True)

                table_columns = [
                    "joint",
                    "n_trials",
                    "mean_of_trial_means_deg",
                    "sd_of_trial_means_deg",
                    "mean_rom_deg",
                    "sd_rom_deg",
                ]

                available_columns = [
                    column for column in table_columns
                    if column in multi_stats_df.columns
                ]

                display_df = multi_stats_df[available_columns].copy()

                rename_map = {
                    "joint": "Joint",
                    "n_trials": "N",
                    "mean_of_trial_means_deg": "Mean",
                    "sd_of_trial_means_deg": "SD",
                    "mean_rom_deg": "Mean ROM",
                    "sd_rom_deg": "SD ROM",
                }

                display_df = display_df.rename(columns=rename_map)

                self.add_dataframe_table(
                    display_df,
                    max_rows=12,
                    font_size=7,
                )

        except Exception:
            self.add_paragraph("Multi-trial statistics could not be loaded.")

        figures_dir = self.project_path / "figures"

        if figures_dir.exists():
            multi_figures = sorted(figures_dir.glob("multi_trial_mean_sd_*.png"))

            if multi_figures:
                self.pdf.add_page()
                self.add_section_title("Multi-Trial Mean ± SD Figure")

                for figure_path in multi_figures[:2]:
                    try:
                        self.pdf.image(str(figure_path), x=15, w=180)
                        self.pdf.ln(5)
                    except Exception:
                        self.add_paragraph(f"Could not insert figure: {figure_path.name}")

    def add_output_files(self) -> None:
        """Add output file summary."""
        self.add_section_title("Output File Summary")
        self.add_file_status_table()

    def generate(self) -> Dict[str, Any]:
        """Generate PDF report and report_info.json."""
        self.report_dir.mkdir(parents=True, exist_ok=True)

        self.add_title_page()
        self.add_camera_recording_information()
        self.add_processing_information()
        self.add_clinical_notes()
        self.add_statistics_table()
        self.add_figures()
        self.add_multi_trial_section()
        self.add_output_files()

        self.pdf.output(str(self.report_path))

        report_info = {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "report_file": str(Path(REPORT_DIRNAME) / REPORT_FILENAME),
            "report_info_file": str(Path(REPORT_DIRNAME) / REPORT_INFO_FILENAME),
            "included_files": {
                "metadata": (self.project_path / METADATA_FILENAME).exists(),
                "processing_info": (self.project_path / PROCESSING_INFO_FILENAME).exists(),
                "kinematics_info": (self.project_path / KINEMATICS_INFO_FILENAME).exists(),
                "statistics": (self.project_path / STATISTICS_FILENAME).exists(),
                "normalized_curves": (self.project_path / NORMALIZED_CURVES_FILENAME).exists(),
                "time_curve_figure": (
                    self.project_path / "figures" / "kinematics_time_curves.png"
                ).exists(),
                "normalized_curve_figure": (
                    self.project_path / "figures" / "kinematics_normalized_curves.png"
                ).exists(),
            },
            "clinical_disclaimer_included": True,
            "angle_convention_included": True,
        }

        save_json(self.report_info_path, report_info)

        return report_info


def generate_report(project_path: Path | str) -> Dict[str, Any]:
    """Convenience function to generate VMotionLab PDF report."""
    generator = ReportGenerator(project_path)
    return generator.generate()